name: Build, Push, and Deploy

on:
  push:
    branches:
      - main   # Runs every time you push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-classifier:latest

  deploy-railway:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Railway CLI
      run: curl -fsSL https://railway.app/install.sh | sh

    - name: Debug Railway Token
      run: echo "Token is set"
      env:
         RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Deploy to Railway
      run: railway up --service=iris-classifier --ci
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
